### ISSUE TITLE
Group middleware route

### ISSUE THREAD

**Issue by ClawdeenFleury** [HE-Arc/calm#70]
Retour sur le rendu intermédiaire sur la partie Routes:
Utiliser un groupe de middleware lorsqu'il y a des routes qui utilisent plusieurs fois le même  :[https://laravel.com/docs/10.x/middleware#middleware-groups](https://laravel.com/docs/10.x/middleware#middleware-groups)

**Comment by ylked** [comment]
on n'utilise qu'un seul Middleware par route, pas de nécessité d'utiliser des groupes
